spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/userAuctionApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

---
spring:
  config:
    activate:
      on-profile: local-db

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
---
spring:
  config:
    activate:
      on-profile: test-db

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
