spring:
  # DB
  datasource:
    url: jdbc:h2:mem:~/userAuctionApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행

  h2:
    console:
      enabled: true

# aws s3
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

  servlet:
    multipart:
      max-file-size: 4MB # 파일 하나 당 최대 사이즈
      max-request-size: 20MB # 요청 당 최대 사이즈
